### ISSUE TITLE
Where to put custom config file

### ISSUE THREAD

**Issue by languitar** [Baggykiin/pass-winmenu#29]
Somehow I can't find information on where to place a custom yaml-based configuration file. The README doesn't indicate where that file has to go to.

**Comment by Baggykiin** [comment]
You can put it in the same directory as the `pass-winmenu.exe` file. However, a config file is generated on startup, so you should be able to edit that one as well.

**Comment by languitar** [comment]
Could you add that to the README? I have installed pass-winmenu via chocolatey. Any idea what happens to my config file on an update?

**Comment by Baggykiin** [comment]
That's still something I'm working out. I was planning to update the config file automatically (as detailed in #25) but I've come to realise that this probably isn't feasible.

Instead, any update that significantly changes the config file format (renaming/moving existing config keys, rather than just adding new ones) will have the application back up your old config file, generate a new config file containing the default settings, and prompt you to manually copy over your changed settings to the new file.

Since this obviously isn't something I want users to be required to do every major update, I'll try to avoid such changes if at all possible.

**Comment by languitar** [comment]
My question was also more concerned regarding the way chocolatey behaves. Does it erase the config file while updating? Or will it stay there? Coming from a Linux background, a config file directly in the program folder for user settings feels weird.

**Comment by Baggykiin** [comment]
To be honest I'm not sure; the Chocolatey package maintainer might know this.
