### ISSUE TITLE
Clipboard Empty (Windows 10)

### ISSUE THREAD

**Issue by danprime** [Baggykiin/pass-winmenu#8]
After seeing notification that the password has been copied to clipboard the paste is empty.

Steps to Replicate:

1. Start Pass-winmenu
1. Hit the Hot Key combo
1. Select the Secret
1. Enter password for decryption key
1. See notification
1. Try to paste from clipboard (Ctrl-V)

ERR empty or clipboard is not loaded.

**Comment by majkinetor** [comment]
Anything in event viewer ?
What happens if you install some clipboard manager such as copyq ?

**Comment by Baggykiin** [comment]
Do you get an error as well, or just an empty clipboard? Would you mind trying out [this build](https://ci.appveyor.com/api/buildjobs/ig7nwwvahlu72kmk/artifacts/pass-winmenu%2Fbin%2Fpass-winmenu.zip) to see if the issue persists?

**Comment by danprime** [comment]
@majkinetor I can't seem to see the logs for Winmenu. Should I look for something specific?

**Comment by danprime** [comment]
@Baggykiin Thanks for looking into this.

No error message. Just the notification that it's been successfully copied but empty clipboard.

I tried the build and it's the same effect (empty clipboard).

**Comment by Baggykiin** [comment]
I've ran into similar issues in the past. The C# clipboard API is notoriously unreliable, often simply failing silently instead of throwing any exceptions. I've made a test build which checks if setting the clipboard text succeeded, and, if not, tries to set it using a different method (Calling WinAPI directly).

Would you mind testing said build to see if that fixes anything? You can download it [here](https://ci.appveyor.com/api/buildjobs/urv4imvaglv0uids/artifacts/pass-winmenu%2Fbin%2Fpass-winmenu.zip).

**Comment by danprime** [comment]
@Baggykiin I totally understand about clipboard API unreliability! 

Unfortunately, the version you sent also does not work. Is there somewhere specific you want me to check for the logs?

**Comment by Baggykiin** [comment]
Sorry for the late reaction, I'm currently on holiday so I won't be able to do much development for the next 2-3 weeks. What I'd like to know is if you got any error messages this time, or did it still fail silently?

It's possible that another application is locking the clipboard, preventing pass-winmenu from accessing it. If you prevent that application from starting on boot, and then reboot your PC (so that it doesn't get a chance to access the clipboard) pass-winmenu might work. Obviously it might be somewhat difficult to figure out which application that is, so you could also try rebooting into safe mode (which does not allow any program to start on boot) and testing again.
Obviously that's not a real solution to your problem, but it might at least help us figure out what's causing it.
